FROM wordpress:latest
ENV WORDPRESS_DB_NAME aurorasql
ENV WORDPRESS_DB_USER admin
ENV WORDPRESS_DB_PASSWORD qwer1234!!
ENV WORDPRESS_DB_HOST database-1.cluster-ro-c6xikmepqgwm.ap-northeast-2.rds.amazonaws.com